# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hi, I'm Hamed 
email: hr277@cornell.edu
description: >- # this means to ignore newlines until "baseurl:"
  Product Manager at Microsoft Teams
url: "https://hamedrabah.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
icon: /assets/images/icon-5121.png

  
# Build settings
markdown: kramdown
show_excerpts: true
hide_credits: true
hide_search: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 3
paginate_path: "/page/:num/"

talkyard_server_url: https://comments-for-amorsapientiae-com.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
